### PR TITLE
lots of changes

### PR DESCRIPTION
**Pull request by srmcconomy**

### CODE REVIEW

**Comment by generalpepper** [comment]
Why did you remove the await from CouncilRoom? Almost everywhere else we draw we have an await
``` js
-    await player.forEachOtherPlayer(async other => await other.draw(1));
 +    await player.forEachOtherPlayer(other => other.draw(1));
```

**Comment by srmcconomy** [comment]
its a combination of things, but short answer is those two lines are equivalent in functionality but the changed one is faster

first of all, arrow functions without braces implicitly return the value. So
```js
other => other.draw(1);
```
is the same as
```js
other => { return other.draw(1); }
```

second, any function marked as `async` implicitly returns a `Promise`, so 
```js
async other => await other.draw(1)
```
is the same as
```js
other => {
  return new Promise((res, rej) => {
    other.draw(1).then(val => res(val));
  });
}
```
(note that `draw` is `async` and so it always returns a `Promise`)
if you know what promises are then you can see that that is equivalent to
```js
other => other.draw(1)
```
so having `async`/`await` there is redundant and adds more overhead

**Comment by srmcconomy** [comment]
https://eslint.org/docs/rules/no-return-await

**Comment by generalpepper** [comment]
Baron doesn't discard an Estate

Baron also only costs 3 not 4

**Comment by generalpepper** [comment]
I also assume you have client files for all of these new cards

**Comment by generalpepper** [comment]
I would prefer resetting actionsPlayedThisTurn at the beginning of the turn with buys and money and stuff but w/e.

**Comment by generalpepper** [comment]
Courtier isn't a Victory card
Should cost 5
predicate: () => true, feels redundant, not 100% sure
You do the choice selecting here differently than in Pawn, both are probably fine but should be the same.

**Comment by generalpepper** [comment]
Diplomat is called `Moat`, also only costs 2 not 4
if (player.hand.size >= 5) check should probably be in shouldReactTo() not reactTo()

**Comment by generalpepper** [comment]
Mill should only gets +2 Coin if you discarded two cards
Needs +1 VP

**Comment by generalpepper** [comment]
MiningVillage or Miningvillage we use both formats?

Isn't a Victory Card

**Comment by generalpepper** [comment]
Patrol doesn't let them choose the order to put back on top of deck

**Comment by generalpepper** [comment]
Swindler
const [supply] = this.selectSupplies({, should be player.selectSupplies

**Comment by generalpepper** [comment]
WishingWell of Wishingwell?
It also falls apart when we get split piles or a supply pile empties but we'll have to deal with that some time. Maybe have some sort of global array created at game start that lists all the cards possible from the current kingdom but this isn't a priority.

**Pull request merged**
